/**
  * @file wm8731.c
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief Device driver for wm8731 device
  *
  */

#include "wm8731.h"



/**
 * @brief initializes device
 * @param dev ptr to wm8731 device
 * @return status 
 */
static mrt_status_t wm_init(wm8731_t* dev)
{   
    /* Initialize Register Descriptors */
    REG_INIT( dev->mLeftIn , WM_REG_LEFT_IN_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mRightIn , WM_REG_RIGHT_IN_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mLeftOut , WM_REG_LEFT_OUT_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mRightOut , WM_REG_RIGHT_OUT_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mAnPath , WM_REG_AN_PATH_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mDigPath , WM_REG_DIG_PATH_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mPowerDwn , WM_REG_POWER_DWN_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mDigIface , WM_REG_DIG_IFACE_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mSample , WM_REG_SAMPLE_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mActive , WM_REG_ACTIVE_ADDR , uint16_t, REG_PERM_RW  );
    REG_INIT( dev->mReset , WM_REG_RESET_ADDR , uint16_t, REG_PERM_RW  );


    /*user-block-init-start*/
    /*user-block-init-end*/

    return MRT_STATUS_OK;
}


mrt_status_t wm_init_i2c(wm8731_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    status = init_i2c_register_device(&dev->mRegDev, i2c, WM8731_I2C_ADDRESS, WM8731_REG_ADDR_SIZE );

    wm_init(dev);


    /*user-block-init-i2c-start*/
    /*user-block-init-i2c-end*/
    
    return MRT_STATUS_OK;
}

mrt_status_t wm_test(wm8731_t* dev)
{
    /*user-block-test-start*/

    /*user-block-test-end*/
    return MRT_STATUS_ERROR;
}


/*user-block-bottom-start*/
/*user-block-bottom-end*/
